apiVersion: v1
kind: Pod
metadata:
    name: just-a-shell
    labels:
        name: just-a-shell
spec:
    containers:
    - name: a-shell
      image: ubuntu
      command: ["/bin/bash", "-c", "while true ; do sleep 10 ; done"]
      volumeMounts:
        - mountPath: "/data"
          name: pv
    - name: another-shell
      image: ubuntu
      command: ["/bin/bash", "-c", "while true ; do sleep 10 ; done"]
      volumeMounts:
      - mountPath: "/data"
        name: pv
    volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: persistent-volume-claim