apiVersion: apps/v1beta2
metadata:
    name: redis
    labels:
        deployment: redis
        
kind: Deployment
spec:
    selector:
        matchlabels:
            pod: redis
    replicas: 1
    template:
        metadata:
            labels:
                pod: redis
        spec:
            containers:
                - name: master
                  image: redis
                  resources:
                    requests:
                        cpu: 100m
                        memory: 100Mi
                  ports:
                    - containerPort: 6379

    