apiVersion: v1
kind: Service
metadata:
    name: postgres-service
spec:
    selector:
        app: postgres-container
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432

#Kubernetes allows the use of the service name i.e. postgres-service for domain name 
#resolution to the pod IP. This means that instead of an IP address we will 
#use postgres_service as the host in order to find our deployed database instance from Django.