kind: PersistentVolume
apiVersion: v1
metadata:
    name: persistent-volume-1
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/tmp/data"
