apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
    name: web
spec:
    serviceName: "nginx"
    replicas: 1
    template:
        metadata:
            labels:
                app: nginx
        spec:
            terminationGracePeriodSeconds: 10
            containers: 
            - name: nginx
              image: gcr.io/google_containers/nginx-slim:0.8
              ports:
              - containerPort: 80
                name: web
              volumeMounts:
              - name: www
                mountPath: /usr/share/nginx/html
    volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
            requests:
                storage: 1Gib

    
                  
            